import { useState, useRef, useEffect, useCallback, useMemo } from 'react'
import { fabric } from 'fabric'
import { useAppStore, useCurrentIndex } from '@/stores/useAppStore'
import { useSettingsStore } from '@/stores/useSettingsStore'
import { type CanvasObject, CopyPlugin, LockPlugin, ObjectPlugin, SelectionType } from '@storige/canvas-core'
import { Image, Type as TextT, Hexagon, Frame as FrameCorners, QrCode, Layers as Stack, X, Trash2 as Trash, Lock as LockSimple, Unlock as LockSimpleOpen, Eye, EyeOff as EyeSlash, GripVertical as DotsSixVertical, Plus, Pin, ShieldCheck, PencilOff, Printer, ArrowUpDown, Copy as CopyIcon, ChevronUp, ChevronDown } from 'lucide-react'
import { cn } from '@/lib/utils'
import { showToast } from '@/stores/useToastStore'
import { Button } from '@/components/ui/button'
import { buildNextMultiSelection, layerStepReorderArgs } from '@/utils/layerPanelSelection'
import { resolveLayerLockState, layerDisplayName, isAutoGeneratedName } from '@/utils/layerDisplay'
import { getAbsoluteAABB, overlappingIdSet, type AABB } from '@/utils/layerOverlap'
import {
  createThumbCache,
  generateObjectThumbnail,
  isThumbEligibleType,
  scheduleIdle,
  THUMBS_PER_IDLE_PASS,
  type FabricThumbSource,
  type ThumbCache,
} from '@/utils/layerThumbnails'
import {
  createLongPressTracker,
  isTouchEnv,
  resolveTouchDropTarget,
  SHEET_SWIPE_CLOSE_PX,
  sidePanelContainerClass,
  type RowRect,
} from '@/utils/layerTouchSheet'

// S3 (공유 계층, 2026-06-23): 레이어 패널 DnD 재정렬.
// 모바일/터치 환경에서는 native HTML5 drag 가 long-press·터치 스크롤과 충돌하므로 비활성.
// L6 (2026-07-11): 터치는 바텀시트 + 롱프레스 터치 DnD 로 대체(isTouchEnv 는 공용 유틸로 이동).
const TOUCH_ENV = isTouchEnv()

// Icon mapping by selection type
const getIconByType = (type: SelectionType) => {
  switch (type) {
    case SelectionType.background:
      return Image
    case SelectionType.frame:
      return FrameCorners
    case SelectionType.group:
      return Stack
    case SelectionType.image:
      return Image
    case SelectionType.shape:
      return Hexagon
    case SelectionType.text:
      return TextT
    case SelectionType.smartCode:
      return QrCode
    default:
      return Hexagon
  }
}

interface SidePanelProps {
  show: boolean
  onClose?: () => void
}

/** L5-①: 객체 목록 필터 — '전체'(기본) | '겹침'(선택 객체와 AABB 교차만) */
type LayerListFilter = 'all' | 'overlap'

/** L5-②: object:modified 이벤트 target 서브셋(ActiveSelection 이면 _objects 전개) */
interface ModifiedTargetLike {
  id?: string
  type?: string
  extensionType?: string
  parentLayerId?: string
  clipPath?: { id?: string }
  _objects?: ModifiedTargetLike[]
}

/** fillImage 동반 객체의 부모(사진틀/모양틀) id — 연결 규약 3종 수용 */
function fillImageParentId(t: ModifiedTargetLike): string | undefined {
  if (t.extensionType !== 'fillImage') return undefined
  if (t.parentLayerId) return t.parentLayerId
  if (t.clipPath?.id) return t.clipPath.id
  if (t.id && t.id.endsWith('_fillImage')) return t.id.slice(0, -'_fillImage'.length)
  return undefined
}

export default function SidePanel({ show, onClose }: SidePanelProps) {
  const canvas = useAppStore((state) => state.canvas)
  const allCanvas = useAppStore((state) => state.allCanvas)
  const objects = useAppStore((state) => state.objects)
  const screenshots = useAppStore((state) => state.screenshots)
  const currentIndex = useCurrentIndex()
  const setPage = useAppStore((state) => state.setPage)
  const deletePage = useAppStore((state) => state.deletePage)
  const addPage = useAppStore((state) => state.addPage)
  const updateObjects = useAppStore((state) => state.updateObjects)
  const getPlugin = useAppStore((state) => state.getPlugin)
  const reorderObject = useAppStore((state) => state.reorderObject)
  // A1-1: 레이어 행 삭제 — S2 확인 모달 공통 경로(ControlBar 휴지통·DEL 핫키와 동일)
  const requestDeleteSelection = useAppStore((state) => state.requestDeleteSelection)

  const pageInfo = useSettingsStore((state) => state.currentSettings.page)
  // B0-② (2026-07-04): 잠금 해제 권한 게이트용 — 관리자 위치고정은 비-editMode 에서 해제 불가
  const editMode = useSettingsStore((state) => state.currentSettings.editMode)

  const [editingObject, setEditingObject] = useState<CanvasObject | null>(null)
  const [editName, setEditName] = useState('')
  const nameInputRef = useRef<HTMLInputElement>(null)

  // T4-① (2026-07-13): '페이지' 섹션은 하단 collapsible 로 강등(기본 접힘) — 헤더 Layers
  // 아이콘이 여는 이 패널의 1차 목적은 레이어('요소')다. 페이지 섹션 제거는 금지:
  // 비-spread 모드에서 페이지 추가/삭제의 유일한 진입점(BookNavigation 은 순수 네비).
  const [pagesExpanded, setPagesExpanded] = useState(false)

  // L2 A-3: 보호 요소 안내 토스트 — 세션당 1회(반복 클릭 시 소음 방지)
  const protectedToastShownRef = useRef(false)

  // S3: 레이어 패널 DnD 재정렬 상태 (데스크톱 전용)
  const [dragSourceId, setDragSourceId] = useState<string | null>(null)
  const [dragOver, setDragOver] = useState<{ id: string; above: boolean } | null>(null)

  // -------------------------------------------------------------------------
  // L5-①: '겹침만 보기' 필터 (Canva Overlapping 패턴 — 순수 뷰 상태)
  // -------------------------------------------------------------------------
  const activeSelection = useAppStore((state) => state.activeSelection)
  const hasSelection = activeSelection.length > 0
  const [listFilter, setListFilter] = useState<LayerListFilter>('all')

  // 선택 해제 시 '겹침' 탭 자동 복귀 — 탭이 켜진 채 전체 목록이 보이는 모순 방지
  useEffect(() => {
    if (!hasSelection && listFilter !== 'all') setListFilter('all')
  }, [hasSelection, listFilter])

  // 표시 행 = {row, orderIndex}. orderIndex 는 전체 목록(objects) 기준 인덱스 —
  // 필터 중에도 ↑↓ 순서변경(layerStepReorderArgs)이 전체 z-order 기준으로 동작해야 한다.
  // 선택 변경(activeSelection)·객체 이동(object:modified→updateObjects→objects 재생성)
  // 모두 이 useMemo 를 재평가시키므로 별도 이벤트 배선 불필요(기존 파이프라인 활용).
  const visibleRows = useMemo(() => {
    const all = objects.map((row, orderIndex) => ({ row, orderIndex }))
    if (listFilter !== 'overlap' || !canvas || activeSelection.length === 0) return all

    const selectionRects = activeSelection
      .map((obj) => getAbsoluteAABB(obj as unknown as { getBoundingRect?: (a?: boolean, c?: boolean) => AABB }))
      .filter((r): r is AABB => r !== null)
    const selectedIds = new Set(
      activeSelection
        .map((obj) => (obj as unknown as { id?: string }).id)
        .filter((id): id is string => typeof id === 'string')
    )
    const liveById = new Map<string, unknown>()
    canvas.getObjects().forEach((obj: { id?: string }) => {
      if (obj.id) liveById.set(obj.id, obj)
    })
    const overlapIds = overlappingIdSet(
      selectionRects,
      selectedIds,
      objects.map((row) => ({
        id: row.id,
        rect: getAbsoluteAABB(liveById.get(row.id) as { getBoundingRect?: (a?: boolean, c?: boolean) => AABB } | undefined),
      }))
    )
    return all.filter(({ row }) => overlapIds.has(row.id))
  }, [objects, listFilter, canvas, activeSelection])

  // -------------------------------------------------------------------------
  // L5-②: 행 미니 썸네일 — 캐시 + object:modified 무효화 + idle 생성
  // -------------------------------------------------------------------------
  const thumbCacheRef = useRef<ThumbCache | null>(null)
  if (thumbCacheRef.current === null) thumbCacheRef.current = createThumbCache()
  // 렌더 재실행 트리거 2종: thumbTick=생성 완료, invalidateTick=무효화(재생성 예약)
  const [, setThumbTick] = useState(0)
  const [invalidateTick, setInvalidateTick] = useState(0)

  // 무효화 배선: object:modified 시에만(스펙) — URL 은 보존(stale-while-revalidate)
  useEffect(() => {
    if (!canvas) return
    const cache = thumbCacheRef.current
    const onModified = (e: fabric.IEvent) => {
      const target = e.target as ModifiedTargetLike | undefined
      if (!target) return
      const targets: ModifiedTargetLike[] =
        target.type === 'activeSelection' && Array.isArray(target._objects) ? target._objects : [target]
      let touched = false
      for (const t of targets) {
        if (t?.id) {
          cache?.invalidate(t.id)
          touched = true
        }
        // fillImage 수정(위치/필터)도 부모 사진틀 썸네일에 반영
        const parentId = t ? fillImageParentId(t) : undefined
        if (parentId) {
          cache?.invalidate(parentId)
          touched = true
        }
      }
      if (touched) setInvalidateTick((t) => t + 1)
    }
    // 사진틀 채움/비움은 frame 의 modified 가 아니라 fillImage 의 added/removed 로만
    // 관측된다 — 부모 틀의 음성 캐시('')를 무효화해 사진 썸네일로 갱신.
    const onFillChanged = (e: fabric.IEvent) => {
      const target = e.target as ModifiedTargetLike | undefined
      const parentId = target ? fillImageParentId(target) : undefined
      if (parentId) {
        cache?.invalidate(parentId)
        setInvalidateTick((t) => t + 1)
      }
    }
    canvas.on('object:modified', onModified)
    canvas.on('object:added', onFillChanged)
    canvas.on('object:removed', onFillChanged)
    return () => {
      canvas.off('object:modified', onModified)
      canvas.off('object:added', onFillChanged)
      canvas.off('object:removed', onFillChanged)
    }
  }, [canvas])

  // 생성 패스: requestIdleCallback 디바운스(objects 변경마다 이전 예약 취소 후 재예약),
  // 패스당 THUMBS_PER_IDLE_PASS 개 상한 — 행 렌더에서는 toDataURL 을 절대 호출하지 않는다.
  useEffect(() => {
    if (!show || !canvas) return
    const cache = thumbCacheRef.current
    if (!cache) return
    let cancelled = false
    let cancelIdle: (() => void) | null = null

    const run = () => {
      if (cancelled) return
      let mutated = false
      let remaining = false
      let budget = THUMBS_PER_IDLE_PASS
      try {
        const live = canvas.getObjects() as unknown as FabricThumbSource[]
        for (const row of objects) {
          if (!isThumbEligibleType(row.type)) continue
          if (cache.get(row.id) !== undefined) continue // fresh(음성 캐시 '' 포함) — 스킵
          if (budget <= 0) {
            remaining = true
            break
          }
          budget -= 1
          const source = live.find((o) => o.id === row.id)
          if (!source) continue
          const url = generateObjectThumbnail(source, live)
          // 실패는 '' 음성 캐시 — 다음 무효화까지 재시도 안 함(아이콘 유지)
          cache.set(row.id, url ?? '')
          if (url) mutated = true
        }
        cache.prune(new Set(objects.map((o) => o.id)))
      } catch (error) {
        console.error('레이어 썸네일 생성 오류:', error)
      }
      if (mutated) setThumbTick((t) => t + 1)
      if (remaining) cancelIdle = scheduleIdle(run)
    }

    cancelIdle = scheduleIdle(run)
    return () => {
      cancelled = true
      cancelIdle?.()
    }
  }, [objects, canvas, show, invalidateTick])

  // Focus input when editing
  useEffect(() => {
    if (editingObject && nameInputRef.current) {
      nameInputRef.current.focus()
      nameInputRef.current.select()
    }
  }, [editingObject])

  // Object actions
  const handleLock = useCallback((e: React.MouseEvent, objectId: string) => {
    e.preventDefault()
    e.stopPropagation()

    const objectPlugin = getPlugin<ObjectPlugin>('ObjectPlugin')
    const object = canvas?.getObjects().find((obj: any) => obj.id === objectId)

    if (object && objectPlugin) {
      objectPlugin.lock(object)
      updateObjects()
    }
  }, [canvas, getPlugin, updateObjects])

  const handleUnlock = useCallback((e: React.MouseEvent, objectId: string) => {
    e.preventDefault()
    e.stopPropagation()

    const objectPlugin = getPlugin<ObjectPlugin>('ObjectPlugin')
    const lockPlugin = getPlugin<LockPlugin>('LockPlugin')
    const object = canvas?.getObjects().find((obj: any) => obj.id === objectId)

    if (object && objectPlugin) {
      // B0-②: 관리자 위치고정(movable===false)은 비-editMode 에서 해제 차단.
      // L1⑥: silent 실패 → 안내 토스트(왜 안 되는지 피드백).
      if (!editMode && (object as any).movable === false) {
        showToast('관리자가 보호한 요소예요. 잠금을 해제할 수 없어요.', 'info')
        return
      }
      const lockInfo = (object as any).lockInfo
      if (lockInfo?.isLocked) {
        // LockPlugin 고급 잠금은 플러그인 경유 해제(내부 canUnlock 검사 + lockInfo 정합 해제).
        lockPlugin?.unlock(object)
      } else {
        objectPlugin.unlock(object)
      }
      updateObjects()
    }
  }, [canvas, getPlugin, updateObjects, editMode])

  const handleVisible = useCallback((e: React.MouseEvent, objectId: string) => {
    e.preventDefault()
    e.stopPropagation()

    const objectPlugin = getPlugin<ObjectPlugin>('ObjectPlugin')
    const object = canvas?.getObjects().find((obj: any) => obj.id === objectId)

    if (object && objectPlugin) {
      objectPlugin.visible(object)
      canvas?.requestRenderAll()
    }
  }, [canvas, getPlugin])

  const handleInvisible = useCallback((e: React.MouseEvent, objectId: string) => {
    e.preventDefault()
    e.stopPropagation()

    const objectPlugin = getPlugin<ObjectPlugin>('ObjectPlugin')
    const object = canvas?.getObjects().find((obj: any) => obj.id === objectId)

    if (object && objectPlugin) {
      // L1④ 대칭 가드: 관리자 보호 객체(위치고정/삭제잠금/내용잠금)는 고객이 숨길 수 없다 —
      // visible=false 는 저장에 영속돼 필수 요소(로고 등) 미인쇄 사고 벡터(삭제 가드와 대칭).
      const o = object as { movable?: boolean; deleteable?: boolean; contentEditable?: boolean }
      if (!editMode && (o.movable === false || o.deleteable === false || o.contentEditable === false)) {
        showToast('관리자가 보호한 요소는 숨길 수 없어요.', 'info')
        return
      }
      objectPlugin.invisible(object)
      canvas?.requestRenderAll()
    }
  }, [canvas, getPlugin, editMode])

  const selectObject = useCallback((objectId: string, e?: React.MouseEvent) => {
    if (!canvas) return
    const object = canvas.getObjects().find((obj: any) => obj.id === objectId)
    if (!object) return

    // A1-2: shift/ctrl(⌘) 클릭 → fabric ActiveSelection 다중선택.
    // ⚠️ fabric 5.5.2 ActiveSelection 드래그는 자식 lockMovementX/Y 를 존중하지 않는다
    //   (layerPanelSelection.test.ts 재현) → 비-editMode 에서 잠긴 객체는 제외
    //   (buildNextMultiSelection 내 가드 — LockPlugin.handleSelection 선례).
    if (e && (e.shiftKey || e.ctrlKey || e.metaKey)) {
      const prev = (canvas.getActiveObjects?.() ?? []) as fabric.Object[]
      // 기존 ActiveSelection 을 먼저 해제해 자식 좌표(그룹 상대)를 절대좌표로 원복한 뒤 재구성
      canvas.discardActiveObject()
      const next = buildNextMultiSelection(prev, object, editMode)
      if (next.length === 1) {
        canvas.setActiveObject(next[0])
      } else if (next.length > 1) {
        canvas.setActiveObject(new fabric.ActiveSelection(next, { canvas }))
      }
      canvas.requestRenderAll()
      return
    }

    // L2 A-3: 보호 요소 행 클릭 — 선택은 허용하되 1회성 안내(내용 편집 가능 여부로 문구 분기)
    if (!editMode && !protectedToastShownRef.current) {
      const o = object as { movable?: boolean; deleteable?: boolean; contentEditable?: boolean; lockInfo?: { isLocked?: boolean; lockLevel?: string } }
      const isProtected =
        o.movable === false || o.deleteable === false || o.contentEditable === false ||
        (o.lockInfo?.isLocked === true && o.lockInfo.lockLevel !== 'user')
      if (isProtected) {
        protectedToastShownRef.current = true
        // 축별 실상에 맞춘 문구(적대 리뷰): 내용잠금 > 위치고정 > 삭제잠금 단독 순.
        showToast(
          o.contentEditable === false
            ? '템플릿 보호 요소예요 — 변경할 수 없어요.'
            : o.movable === false
              ? '템플릿 보호 요소예요 — 내용만 변경할 수 있어요.'
              : o.deleteable === false
                ? '템플릿 보호 요소예요 — 삭제만 잠겨 있어요.'
                : '템플릿 보호 요소예요.',
          'info'
        )
      }
    }

    canvas.setActiveObject(object)
    canvas.renderAll()
  }, [canvas, editMode])

  // A1-1: 레이어 행 삭제 버튼 — 대상 객체를 먼저 선택한 뒤 공통 경로(requestDeleteSelection)
  // 호출 → S2 확인 모달 → ObjectPlugin.del() (삭제잠금·lid·fillImage 동반제거 가드 그대로).
  const handleDeleteObject = useCallback((e: React.MouseEvent, objectId: string) => {
    e.preventDefault()
    e.stopPropagation()

    const object = canvas?.getObjects().find((obj: any) => obj.id === objectId)
    if (!object) return
    // 삭제잠금(deleteable===false)은 고객(비-editMode) 진입 시 차단 — 버튼 disabled 와 이중 방어
    if (!editMode && (object as any).deleteable === false) {
      showToast('관리자가 보호한 요소는 삭제할 수 없어요.', 'info')
      return
    }

    canvas?.setActiveObject(object)
    canvas?.requestRenderAll()
    requestDeleteSelection()
  }, [canvas, editMode, requestDeleteSelection])

  // A1-1: 레이어 행 복제 버튼 — CopyPlugin.clone(기존 ctrl+d 핫키 로직) 재사용, 시그니처 불변.
  // 복제 후 목록 갱신은 canvas 'object:added' → _updateObjectsHandler 가 처리(직접 호출 불필요).
  const handleDuplicateObject = useCallback((e: React.MouseEvent, objectId: string) => {
    e.preventDefault()
    e.stopPropagation()

    const object = canvas?.getObjects().find((obj: any) => obj.id === objectId)
    if (!object) return
    // L1④ 대칭 가드: 보호 객체(비-editMode)는 복제 차단 — 보호 플래그가 사본에 복사되더라도
    // 필수 요소 중복 배치는 디자인/인쇄 오염(삭제·숨김 가드와 대칭).
    const o = object as { movable?: boolean; deleteable?: boolean; contentEditable?: boolean }
    if (!editMode && (o.movable === false || o.deleteable === false || o.contentEditable === false)) {
      showToast('관리자가 보호한 요소는 복제할 수 없어요.', 'info')
      return
    }
    getPlugin<CopyPlugin>('CopyPlugin')?.clone(object)
  }, [canvas, getPlugin, editMode])

  // A1-3: 모바일(TOUCH_ENV) ↑↓ 순서변경 — reorderObject 재사용(fabric 라이브 스택 기준,
  // reverse 방향 함정·fillImage 동반이동·setUnchangeable 재고정·updateObjects 전부 내장).
  const handleStepReorder = useCallback((e: React.MouseEvent, index: number, dir: 'up' | 'down') => {
    e.preventDefault()
    e.stopPropagation()

    const args = layerStepReorderArgs(objects, index, dir)
    if (!args) return
    reorderObject(objects[index].id, args.targetId, args.placeAbove)
  }, [objects, reorderObject])

  const startEditing = (obj: CanvasObject) => {
    // L1④ 대칭 가드: 보호 객체(비-editMode)는 이름변경 진입 차단(레이어 식별 오염 방지).
    if (!editMode && (obj.movable === false || obj.deleteable === false || obj.contentEditable === false)) {
      showToast('관리자가 보호한 요소는 이름을 바꿀 수 없어요.', 'info')
      return
    }
    setEditingObject(obj)
    // L2: 자동 생성 이름(textbox3 등)은 빈칸으로 seed — 행 표시명(미리보기/타입명)과
    // 프리필이 어긋나는 혼동 방지. 사용자 지정 이름은 그대로 편집.
    setEditName(obj.name && !isAutoGeneratedName(obj.name) ? obj.name : '')
  }

  const finishEditing = () => {
    if (editingObject && editName.trim()) {
      const fabricObject = canvas?.getObjects().find((obj: any) => obj.id === editingObject.id)
      // L1④: commit 경로 이중 가드 — startEditing 차단과 대칭(리뷰 지적, 유일 진입이지만 방어적).
      const o = fabricObject as { movable?: boolean; deleteable?: boolean; contentEditable?: boolean } | undefined
      const isProtected = !editMode && !!o && (o.movable === false || o.deleteable === false || o.contentEditable === false)
      if (fabricObject && !isProtected) {
        fabricObject.set('name', editName.trim())
      }
    }
    setEditingObject(null)
    updateObjects()
  }

  const cancelEditing = () => {
    setEditingObject(null)
  }

  // Page actions
  const handleAddPage = useCallback(() => {
    const maxPages = pageInfo?.max || 100
    if (allCanvas.length >= maxPages) {
      alert(`페이지는 최대 ${maxPages}개까지 생성할 수 있습니다.`)
      return
    }
    addPage()
  }, [pageInfo, allCanvas.length, addPage])

  const handleDeletePage = useCallback((e: React.MouseEvent, canvasId: string) => {
    e.preventDefault()
    e.stopPropagation()

    const minPages = pageInfo?.min || 1
    if (allCanvas.length <= minPages) {
      return
    }

    try {
      deletePage(canvasId)
    } catch (error) {
      console.error('페이지 삭제 오류:', error)
    }
  }, [pageInfo, allCanvas.length, deletePage])

  const handleSetPage = useCallback((index: number) => {
    if (currentIndex !== index) {
      setPage(index)
    }
  }, [currentIndex, setPage])

  // S3: 레이어 DnD 핸들러 (데스크톱 전용 — 모바일은 dragEnabled=false 로 미부여)
  // ⚠️ 단일 진실원(R2): 목록은 z-order reverse 라 "위 = 맨앞". 따라서 target 카드 상단 절반에
  //    드롭 = source 를 그 위(앞/front)로 → reorderObject(.., placeAbove=true). 하단 절반 = 뒤.
  const dragEnabled = !TOUCH_ENV

  const handleObjDragStart = (objectId: string) => (e: React.DragEvent<HTMLDivElement>) => {
    if (!dragEnabled) return
    setDragSourceId(objectId)
    try {
      e.dataTransfer.effectAllowed = 'move'
      // 일부 브라우저는 setData 없으면 dragstart 가 무시됨
      e.dataTransfer.setData('text/plain', objectId)
    } catch {
      // 무시
    }
  }

  const handleObjDragOver = (objectId: string) => (e: React.DragEvent<HTMLDivElement>) => {
    if (!dragEnabled || dragSourceId === null || objectId === dragSourceId) return
    e.preventDefault()
    e.dataTransfer.dropEffect = 'move'
    const rect = e.currentTarget.getBoundingClientRect()
    const above = e.clientY < rect.top + rect.height / 2
    setDragOver((prev) =>
      prev && prev.id === objectId && prev.above === above ? prev : { id: objectId, above }
    )
  }

  const handleObjDragLeave = (objectId: string) => () => {
    setDragOver((prev) => (prev && prev.id === objectId ? null : prev))
  }

  const handleObjDrop = (objectId: string) => (e: React.DragEvent<HTMLDivElement>) => {
    if (!dragEnabled || dragSourceId === null) {
      setDragSourceId(null)
      setDragOver(null)
      return
    }
    e.preventDefault()
    e.stopPropagation()
    const source = dragSourceId
    setDragSourceId(null)
    setDragOver(null)
    if (source === objectId) return
    const rect = e.currentTarget.getBoundingClientRect()
    const above = e.clientY < rect.top + rect.height / 2
    // L2 A-6: 순서 잠금 '소스' 드래그는 reorderObject 내부 가드(source 만 검사)가
    // silent 차단 — 같은 조건으로 사유 안내. target 옆 드롭은 기존대로 허용(과다 차단 금지).
    const src = objects.find((o) => o.id === source)
    if (src?.lockLayerOrder === true) {
      showToast('순서가 잠긴 요소예요 — 순서를 바꿀 수 없어요.', 'info')
      return
    }
    reorderObject(source, objectId, above)
  }

  const handleObjDragEnd = () => {
    setDragSourceId(null)
    setDragOver(null)
  }

  // -------------------------------------------------------------------------
  // L6: 터치 롱프레스 DnD (TOUCH_ENV 전용 — HTML5 DnD 는 터치 미지원)
  // 롱프레스(~350ms, 이동 시 취소=스크롤 양보) 후에만 드래그 모드 진입.
  // 드래그 모드에서는 touchmove preventDefault(비-passive)로 시트 스크롤을 잠그고
  // 기존 dragSourceId/dragOver 상태를 재사용해 삽입 라인 인디케이터를 그린다.
  // 드롭은 데스크톱과 동일 시맨틱으로 reorderObject 재사용(fabric 라이브 스택 기준).
  // -------------------------------------------------------------------------
  // T4-③: 행 요소 맵은 터치 DnD(collectRowRects) 외에 패널 열림 시 선택 행
  // scrollIntoView 에도 쓰므로 데스크톱에서도 항상 ref 를 부착한다(수집 자체는 무비용).
  const rowElsRef = useRef(new Map<string, HTMLElement>())
  const rowRefCbsRef = useRef(new Map<string, (el: HTMLElement | null) => void>())
  const getRowRef = (id: string) => {
    let cb = rowRefCbsRef.current.get(id)
    if (!cb) {
      cb = (el: HTMLElement | null) => {
        if (el) rowElsRef.current.set(id, el)
        else rowElsRef.current.delete(id)
      }
      rowRefCbsRef.current.set(id, cb)
    }
    return cb
  }

  // T4-③ (2026-07-13): 패널 열림(show false→true) 전환 시 activeSelection 이 있으면
  // 선택 행을 목록 뷰포트로 1회 스크롤({block:'nearest'} — 과스크롤 금지). 열림 전환
  // 1회만 발화 — 패널이 열려 있는 동안의 선택 변경은 스크롤을 흔들지 않는다.
  const prevShowRef = useRef(show)
  useEffect(() => {
    const wasShown = prevShowRef.current
    prevShowRef.current = show
    if (!show || wasShown) return
    const selectedId = (activeSelection[0] as unknown as { id?: string } | undefined)?.id
    if (!selectedId) return
    rowElsRef.current.get(selectedId)?.scrollIntoView?.({ block: 'nearest' })
  }, [show, activeSelection])

  // 드래그 활성 후 touchend 가 합성 click 으로 이어져 selectObject 가 오발동하는 것 방지
  const suppressRowClickRef = useRef(false)
  const touchDragCleanupRef = useRef<(() => void) | null>(null)

  // 언마운트/페이지 전환 시 잔여 document 리스너·드래그 상태 정리
  useEffect(() => () => touchDragCleanupRef.current?.(), [])

  const collectRowRects = useCallback((): RowRect[] => {
    const rows: RowRect[] = []
    rowElsRef.current.forEach((el, id) => {
      const r = el.getBoundingClientRect()
      rows.push({ id, top: r.top, height: r.height })
    })
    return rows
  }, [])

  const handleRowTouchStart = (objectId: string) => (e: React.TouchEvent<HTMLDivElement>) => {
    if (!TOUCH_ENV || e.touches.length !== 1) return
    if (editingObject?.id === objectId) return
    // 행 내부 버튼/입력 위 롱프레스는 드래그로 승격하지 않는다(버튼 오조작 방지)
    if ((e.target as HTMLElement | null)?.closest?.('button, input')) return

    // 이전 제스처 잔여 정리(멀티터치·비정상 종료 방어)
    touchDragCleanupRef.current?.()

    const touch = e.touches[0]
    let dragActive = false
    const tracker = createLongPressTracker({
      onActivate: () => {
        dragActive = true
        suppressRowClickRef.current = true
        setDragSourceId(objectId)
      },
    })

    const teardown = () => {
      tracker.cancel()
      document.removeEventListener('touchmove', onMove)
      document.removeEventListener('touchend', onEnd)
      document.removeEventListener('touchcancel', onCancel)
      touchDragCleanupRef.current = null
      if (dragActive) {
        dragActive = false
        setDragSourceId(null)
        setDragOver(null)
        // 합성 click 은 touchend 직후 동기 발화 — 발화 안 한 경우(preventDefault)에도
        // 플래그가 다음 정상 탭을 삼키지 않도록 태스크 큐에서 해제
        setTimeout(() => {
          suppressRowClickRef.current = false
        }, 0)
      }
    }

    const onMove = (ev: TouchEvent) => {
      const t = ev.touches[0]
      if (!t) return
      if (!dragActive) {
        // 활성 전 허용 반경 초과 = 스크롤 의도 → 롱프레스 취소(스크롤 방해 금지)
        if (tracker.move(t.clientX, t.clientY) === 'cancelled') teardown()
        return
      }
      // 드래그 모드: 시트 스크롤 차단(passive:false 필수) + 삽입 위치 계산
      ev.preventDefault()
      const target = resolveTouchDropTarget(t.clientY, collectRowRects(), objectId)
      setDragOver((prev) =>
        target
          ? prev && prev.id === target.targetId && prev.above === target.above
            ? prev
            : { id: target.targetId, above: target.above }
          : null
      )
    }

    const onEnd = (ev: TouchEvent) => {
      if (dragActive) {
        // 합성 click(selectObject 오발동) 차단 — suppressRowClickRef 와 이중 방어
        ev.preventDefault()
        const t = ev.changedTouches[0]
        if (t) {
          const target = resolveTouchDropTarget(t.clientY, collectRowRects(), objectId)
          if (target) {
            // L2 A-6 동일 가드: 순서 잠금 source 는 reorderObject 내부 silent 차단 — 사유 안내
            const src = objects.find((o) => o.id === objectId)
            if (src?.lockLayerOrder === true) {
              showToast('순서가 잠긴 요소예요 — 순서를 바꿀 수 없어요.', 'info')
            } else {
              reorderObject(objectId, target.targetId, target.above)
            }
          }
        }
      }
      teardown()
    }

    const onCancel = () => teardown()

    touchDragCleanupRef.current = teardown
    document.addEventListener('touchmove', onMove, { passive: false })
    document.addEventListener('touchend', onEnd)
    document.addEventListener('touchcancel', onCancel)
    tracker.start(touch.clientX, touch.clientY)
  }

  // L6: 바텀시트 핸들 스와이프 다운 닫힘(핸들 영역 한정 — 목록 스크롤과 무충돌)
  const sheetSwipeStartYRef = useRef<number | null>(null)
  const handleSheetHandleTouchStart = (e: React.TouchEvent<HTMLDivElement>) => {
    sheetSwipeStartYRef.current = e.touches[0]?.clientY ?? null
  }
  const handleSheetHandleTouchEnd = (e: React.TouchEvent<HTMLDivElement>) => {
    const startY = sheetSwipeStartYRef.current
    sheetSwipeStartYRef.current = null
    const endY = e.changedTouches[0]?.clientY
    if (startY !== null && endY !== undefined && endY - startY > SHEET_SWIPE_CLOSE_PX) {
      onClose?.()
    }
  }

  // L6: 터치 행 액션 상시 노출 — hover 불가 환경, 터치 타깃 ≥40px(h-10 w-10)
  const actionBtnClass = TOUCH_ENV ? 'h-10 w-10' : 'h-7 w-7'

  return (
    <div className={sidePanelContainerClass(TOUCH_ENV, show)}>
      {/* L6: 터치=바텀시트 드래그 핸들(스와이프 다운 닫힘)+닫기 / 비터치=기존 모바일 닫기 바 */}
      {TOUCH_ENV ? (
        <div
          className="top relative flex flex-col items-center pt-2.5 pb-1.5 w-full border-b border-editor-border touch-none"
          onTouchStart={handleSheetHandleTouchStart}
          onTouchEnd={handleSheetHandleTouchEnd}
          role="button"
          aria-label="레이어 시트 핸들 — 아래로 밀어 닫기"
        >
          <div className="sheet-handle h-1 w-10 rounded-full bg-editor-border" aria-hidden="true" />
          <Button
            variant="ghost"
            size="icon"
            className="absolute right-1 top-0.5 h-10 w-10"
            onClick={onClose}
            aria-label="레이어 시트 닫기"
          >
            <X className="h-5 w-5" />
          </Button>
        </div>
      ) : (
        // T4-② (2026-07-13): 데스크톱에서도 보이는 '레이어' 제목+닫기 헤더 — 구 닫기 바는
        // lg:hidden 이라 데스크톱(≥1024px)에서 제목조차 없어 "페이지 네비"로 오인됐다.
        <div className="top flex items-center justify-between pl-4 pr-2 py-2 w-full border-b border-editor-border">
          <h2 className="text-sm font-semibold text-editor-text">레이어</h2>
          <Button variant="ghost" size="icon" className="h-8 w-8" onClick={onClose} aria-label="레이어 패널 닫기">
            <X className="h-5 w-5" />
          </Button>
        </div>
      )}

      {/* Objects Section — T4-①: 레이어('요소')가 이 패널의 1차 목적이라 최상단 배치 */}
      {canvas && (
        <div
          id="objects"
          className={
            // L6: 터치 드래그 모드 중 시트 스크롤 잠금(preventDefault 와 이중 방어)
            TOUCH_ENV
              ? cn('flex-1 pb-4', dragSourceId ? 'overflow-hidden' : 'overflow-y-auto')
              : 'flex-1 overflow-y-auto pb-4'
          }
        >
          <div className="section-header flex items-center justify-between px-4 py-2">
            <h3 className="text-sm font-semibold text-editor-text">요소</h3>
            {/* L5-①: 전체|겹침 토글 — 겹침은 선택 객체와 AABB 교차 행만(Canva Overlapping) */}
            <div className="filter-tabs flex items-center gap-0.5 rounded-md bg-editor-hover p-0.5" role="tablist" aria-label="요소 목록 필터">
              <button
                type="button"
                role="tab"
                aria-selected={listFilter === 'all'}
                className={cn(
                  'px-2 py-0.5 rounded text-[11px] leading-4 transition-colors',
                  listFilter === 'all'
                    ? 'bg-white text-editor-text shadow-sm font-semibold'
                    : 'text-editor-text-muted hover:text-editor-text'
                )}
                onClick={() => setListFilter('all')}
              >
                전체
              </button>
              <button
                type="button"
                role="tab"
                aria-selected={listFilter === 'overlap'}
                disabled={!hasSelection}
                title={hasSelection ? '선택한 요소와 겹치는 요소만 표시' : '객체를 선택하면 겹치는 요소만 볼 수 있어요'}
                className={cn(
                  'px-2 py-0.5 rounded text-[11px] leading-4 transition-colors',
                  listFilter === 'overlap'
                    ? 'bg-white text-editor-text shadow-sm font-semibold'
                    : 'text-editor-text-muted hover:text-editor-text',
                  !hasSelection && 'opacity-40 cursor-not-allowed hover:text-editor-text-muted'
                )}
                onClick={() => setListFilter('overlap')}
              >
                겹침
              </button>
            </div>
          </div>

          {objects.length === 0 ? (
            <div className="px-4 py-8 text-center text-editor-text-muted text-sm">
              요소가 없습니다.
            </div>
          ) : visibleRows.length === 0 ? (
            // L5-①: 선택 객체가 목록 은폐 대상(보호/구조 요소)이라 겹침 결과가 빈 경우
            <div className="px-4 py-8 text-center text-editor-text-muted text-sm">
              선택한 요소와 겹치는 요소가 없습니다.
            </div>
          ) : (
            <div className="items px-3">
              {visibleRows.map(({ row: obj, orderIndex: index }) => {
                const Icon = getIconByType(obj.type)
                // L2 A-2: 감산형 — 고객(비-editMode) 보호 행은 조작 버튼 자체를 제거
                const lockState = resolveLayerLockState(obj)
                const hideCustomerActions = !editMode && lockState === 'protected'
                // L5-②: 캐시 조회만(생성은 idle 패스 전담) — stale 값으로 깜빡임 방지,
                // 미생성/실패('')는 기존 타입 아이콘 유지(빈칸 금지)
                const thumbUrl = isThumbEligibleType(obj.type)
                  ? thumbCacheRef.current?.get(obj.id) || thumbCacheRef.current?.getStale(obj.id) || null
                  : null
                return (
                  <div
                    key={obj.id}
                    ref={getRowRef(obj.id)} /* T4-③: 터치 DnD + 열림 시 scrollIntoView 공용 */
                    draggable={dragEnabled && editingObject?.id !== obj.id}
                    onDragStart={dragEnabled ? handleObjDragStart(obj.id) : undefined}
                    onDragOver={dragEnabled ? handleObjDragOver(obj.id) : undefined}
                    onDragLeave={dragEnabled ? handleObjDragLeave(obj.id) : undefined}
                    onDrop={dragEnabled ? handleObjDrop(obj.id) : undefined}
                    onDragEnd={dragEnabled ? handleObjDragEnd : undefined}
                    onTouchStart={TOUCH_ENV ? handleRowTouchStart(obj.id) : undefined}
                    className={cn(
                      'object-item w-full flex flex-row items-center gap-1 p-1 justify-between',
                      'rounded-lg mb-2 cursor-pointer border border-transparent',
                      'hover:bg-editor-hover group',
                      obj.selected && 'bg-editor-accent/10 border-editor-accent/10',
                      // S3: 드래그 중 source 흐리게 + 드롭 위치 힌트(위/아래 경계선)
                      dragSourceId === obj.id && 'opacity-40',
                      dragOver?.id === obj.id && dragOver.above && 'border-t-2 border-t-editor-accent',
                      dragOver?.id === obj.id && !dragOver.above && 'border-b-2 border-b-editor-accent'
                    )}
                    onClick={(e) => {
                      // L6: 롱프레스 드래그 직후의 합성 click 은 선택으로 처리하지 않는다
                      if (suppressRowClickRef.current) {
                        suppressRowClickRef.current = false
                        return
                      }
                      selectObject(obj.id, e)
                    }}
                    onDoubleClick={() => startEditing(obj)}
                  >
                    <div className="left flex flex-row gap-2 flex-1 items-center overflow-hidden">
                      <div className="drag-handle flex items-center cursor-move opacity-50">
                        <DotsSixVertical className="h-4 w-4 text-editor-text-muted" />
                      </div>
                      {/* L5-②: 이미지·도형류는 24px 미니 썸네일(아이콘 fallback) */}
                      {thumbUrl ? (
                        <img
                          src={thumbUrl}
                          alt=""
                          aria-hidden="true"
                          draggable={false}
                          className="h-6 w-6 rounded border border-editor-border/40 bg-white object-contain flex-shrink-0"
                        />
                      ) : (
                        <Icon className="h-5 w-5 text-editor-text flex-shrink-0" />
                      )}
                      <div className="flex-1 overflow-hidden">
                        {editingObject?.id === obj.id ? (
                          <input
                            ref={nameInputRef}
                            type="text"
                            value={editName}
                            onChange={(e) => setEditName(e.target.value)}
                            onBlur={finishEditing}
                            onKeyUp={(e) => {
                              if (e.key === 'Enter') finishEditing()
                              if (e.key === 'Escape') cancelEditing()
                            }}
                            className="object-name-input w-full text-xs bg-transparent border-none outline-none"
                          />
                        ) : (
                          <span className="name text-xs text-editor-text truncate block">
                            {layerDisplayName(obj)}
                          </span>
                        )}
                      </div>
                      {/* L2 A-2/B-4: 배지 — 고객은 2어휘 상태 1개(템플릿 보호/내 잠금),
                          디자이너(editMode)는 축별 상세 배지 + 한국어 툴팁(ShieldCheck=잠김 통일) */}
                      <div className="badges flex items-center gap-0.5 shrink-0">
                        {!editMode ? (
                          <>
                            {resolveLayerLockState(obj) === 'protected' && (
                              <span title="템플릿 보호 — 디자이너가 보호한 요소"><ShieldCheck className="h-3 w-3 text-editor-text-muted" aria-label="템플릿 보호" /></span>
                            )}
                            {resolveLayerLockState(obj) === 'mine' && (
                              <span title="내 잠금 — 행에서 해제할 수 있어요"><LockSimple className="h-3 w-3 text-blue-500" aria-label="내 잠금" /></span>
                            )}
                          </>
                        ) : (
                          <>
                            {obj.lockLevel && (
                              <span
                                title={`보호 레벨: ${obj.lockLevel === 'designer' ? '디자이너' : obj.lockLevel === 'admin' ? '관리자' : obj.lockLevel === 'system' ? '시스템' : '사용자'}`}
                                className="text-[9px] leading-none px-1 py-0.5 rounded bg-amber-500/15 text-amber-600 font-semibold"
                              >
                                {obj.lockLevel}
                              </span>
                            )}
                            {obj.movable === false && (
                              <span title="위치 고정 — 고객 이동·변형 불가"><Pin className="h-3 w-3 text-amber-500" aria-label="위치 고정" /></span>
                            )}
                            {obj.deleteable === false && (
                              <span title="삭제 잠금 — 고객 삭제 불가"><ShieldCheck className="h-3 w-3 text-amber-500" aria-label="삭제 잠금" /></span>
                            )}
                            {obj.contentEditable === false && (
                              <span title="내용 잠금 — 고객 내용 수정 불가"><PencilOff className="h-3 w-3 text-amber-500" aria-label="내용 잠금" /></span>
                            )}
                            {obj.printExclude === true && (
                              <span title="인쇄 제외 — 화면에만 표시"><Printer className="h-3 w-3 text-amber-500" aria-label="인쇄 제외" /></span>
                            )}
                            {obj.lockLayerOrder === true && (
                              <span title="순서 잠금 — 레이어 순서 변경 불가"><ArrowUpDown className="h-3 w-3 text-amber-500" aria-label="순서 잠금" /></span>
                            )}
                          </>
                        )}
                      </div>
                    </div>
                    {/* A1-3: 모바일(TOUCH_ENV) ↑↓ 순서변경 — hover 가 없는 터치 환경이라 상시 표시 */}
                    {TOUCH_ENV && obj.editable && (
                      <div className="mobile-reorder flex flex-col items-center shrink-0">
                        <Button
                          variant="ghost"
                          size="icon"
                          className="h-4 w-6"
                          disabled={index === 0 || obj.lockLayerOrder === true}
                          onClick={(e) => handleStepReorder(e, index, 'up')}
                          aria-label="앞으로 가져오기"
                        >
                          <ChevronUp className="h-3 w-3" />
                        </Button>
                        <Button
                          variant="ghost"
                          size="icon"
                          className="h-4 w-6"
                          disabled={index === objects.length - 1 || obj.lockLayerOrder === true}
                          onClick={(e) => handleStepReorder(e, index, 'down')}
                          aria-label="뒤로 보내기"
                        >
                          <ChevronDown className="h-3 w-3" />
                        </Button>
                      </div>
                    )}
                    <div className={TOUCH_ENV ? 'right shrink-0' : 'right w-16 h-[30px] relative shrink-0'}>
                      {obj.editable && (
                        /* A1-1: 4버튼(복제·삭제·잠금·표시)이 w-16 을 넘어 왼쪽으로 확장되므로
                           행 hover 배경과 같은 색을 깔아 이름/배지 위에 겹쳐도 읽히게 한다.
                           L6: 터치는 hover 부재 — 인라인 상시 노출(≥40px 타깃, 오버레이 배경 불필요) */
                        <div
                          className={
                            TOUCH_ENV
                              ? 'actions flex items-center gap-0'
                              : 'actions absolute right-0 top-0 bottom-0 m-auto flex gap-1 opacity-0 group-hover:opacity-100 transition-opacity bg-editor-hover rounded-lg'
                          }
                        >
                          {/* L2 A-2 감산형: 고객 보호 행은 복제 버튼 미렌더 (L1 disabled 에서 승격) */}
                          {!hideCustomerActions && (
                            <Button
                              variant="ghost"
                              size="icon"
                              className={actionBtnClass}
                              title="복제"
                              onClick={(e) => handleDuplicateObject(e, obj.id)}
                            >
                              <CopyIcon className="h-4 w-4" />
                            </Button>
                          )}
                          {/* L2 A-2 감산형: 고객 보호 행은 삭제 버튼 미렌더 (A1 disabled 에서 승격) */}
                          {!hideCustomerActions && (
                            <Button
                              variant="ghost"
                              size="icon"
                              className={actionBtnClass}
                              title="삭제"
                              onClick={(e) => handleDeleteObject(e, obj.id)}
                            >
                              <Trash className="h-4 w-4" />
                            </Button>
                          )}
                          {/* L2 A-2: 고객 보호 행은 잠금/해제 버튼 미렌더(B0-② 숨김에서 확장).
                              '내 잠금'(mine) 행은 항상 해제 가능(A-5 행 해제 경로 보장). */}
                          {!hideCustomerActions &&
                            (obj.locked ? (
                              <Button
                                variant="ghost"
                                size="icon"
                                className={actionBtnClass}
                                title="잠금 해제"
                                onClick={(e) => handleUnlock(e, obj.id)}
                              >
                                <LockSimple className="h-4 w-4" />
                              </Button>
                            ) : (
                              <Button
                                variant="ghost"
                                size="icon"
                                className={actionBtnClass}
                                title="잠금"
                                onClick={(e) => handleLock(e, obj.id)}
                              >
                                <LockSimpleOpen className="h-4 w-4" />
                              </Button>
                            ))}
                          {/* L2 A-2 감산형: 고객 보호 행은 숨김 버튼 미렌더 (L1 disabled 에서 승격) */}
                          {hideCustomerActions ? null : obj.visible ? (
                            <Button
                              variant="ghost"
                              size="icon"
                              className={actionBtnClass}
                              title="숨기기"
                              onClick={(e) => handleInvisible(e, obj.id)}
                            >
                              <Eye className="h-4 w-4" />
                            </Button>
                          ) : (
                            <Button
                              variant="ghost"
                              size="icon"
                              className={actionBtnClass}
                              onClick={(e) => handleVisible(e, obj.id)}
                            >
                              <EyeSlash className="h-4 w-4" />
                            </Button>
                          )}
                        </div>
                      )}
                    </div>
                  </div>
                )
              })}
            </div>
          )}
        </div>
      )}

      <hr className="border-editor-border mx-4" />

      {/* Pages Section — T4-①: 하단 collapsible(기본 접힘). 제거 금지 — 비-spread 모드에서
          페이지 추가/삭제의 유일한 진입점(BookNavigation 은 순수 네비). */}
      {canvas && pageInfo && (
        <div id="pages" className="shrink-0">
          <div className="section-header flex items-center justify-between px-4 py-2">
            <button
              type="button"
              className="flex items-center gap-1 text-sm font-semibold text-editor-text"
              onClick={() => setPagesExpanded((v) => !v)}
              aria-expanded={pagesExpanded}
              aria-controls="pages-items"
            >
              {pagesExpanded ? (
                <ChevronUp className="h-4 w-4 text-editor-text-muted" aria-hidden="true" />
              ) : (
                <ChevronDown className="h-4 w-4 text-editor-text-muted" aria-hidden="true" />
              )}
              페이지
            </button>
            {/* 접힘 중 페이지 추가는 결과가 안 보여 오조작 — 펼친 상태에서만 노출 */}
            {pagesExpanded && (
              <Button variant="ghost" size="icon" onClick={handleAddPage} aria-label="페이지 추가">
                <Plus className="h-4 w-4" />
              </Button>
            )}
          </div>
          {pagesExpanded && (
            <div
              id="pages-items"
              className={TOUCH_ENV ? 'overflow-y-auto max-h-[20vh]' : 'overflow-y-auto max-h-[440px]'}
            >
              <div className="items px-4 pb-2">
                {allCanvas.map((c, index) => (
                  <div
                    key={c.id || `page-${index}`}
                    className={cn(
                      'page w-full flex flex-col items-center cursor-pointer relative mb-2',
                      c.id === canvas.id && 'selected'
                    )}
                    onClick={() => handleSetPage(index)}
                  >
                    <div className="page-drag-handle absolute top-1 left-1 cursor-move opacity-0 hover:opacity-100">
                      <DotsSixVertical className="h-4 w-4 text-editor-text-muted" />
                    </div>
                    <div
                      className={cn(
                        'screenshot-box w-full h-[120px] flex items-center justify-center',
                        'bg-white rounded-xl border-2 overflow-hidden relative',
                        c.id === canvas.id ? 'border-editor-accent/60' : 'border-editor-border/10'
                      )}
                    >
                      {(pageInfo.min || 1) < allCanvas.length && (
                        <Button
                          variant="ghost"
                          size="icon"
                          className={cn(
                            'delete-btn absolute top-1 right-1 h-8 w-8',
                            // L6: 터치는 hover 불가 — 상시 노출(반투명 바탕으로 썸네일 위 가독 확보)
                            TOUCH_ENV ? 'opacity-100 bg-white/70' : 'opacity-0 hover:opacity-100'
                          )}
                          onClick={(e) => handleDeletePage(e, c.id)}
                        >
                          <Trash className="h-4 w-4" />
                        </Button>
                      )}
                      {screenshots[index] ? (
                        <img
                          src={screenshots[index]}
                          alt={`Page ${index + 1}`}
                          className="screenshot w-full h-full object-cover"
                        />
                      ) : (
                        <div className="screenshot w-full h-full bg-white" />
                      )}
                    </div>
                    <div className="name text-xs text-editor-text mt-1 truncate w-full text-center">
                      {(c as any).name || `Page ${index + 1}`}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  )
}
