import { describe, it, expect } from 'vitest'
import { SelectionType } from '@storige/canvas-core'
import {
  resolveLayerLockState,
  layerDisplayName,
  selectionTypeLabel,
  isAutoGeneratedName,
} from './layerDisplay'

describe('resolveLayerLockState — 잠금 2어휘 렌즈 (L2)', () => {
  it('보호 축(movable/deleteable/contentEditable=false)은 protected', () => {
    expect(resolveLayerLockState({ movable: false })).toBe('protected')
    expect(resolveLayerLockState({ deleteable: false })).toBe('protected')
    expect(resolveLayerLockState({ contentEditable: false })).toBe('protected')
  })

  it('designer+ 레벨 고급잠금은 protected, user 레벨은 mine', () => {
    expect(resolveLayerLockState({ lockLevel: 'designer' })).toBe('protected')
    expect(resolveLayerLockState({ lockLevel: 'admin' })).toBe('protected')
    expect(resolveLayerLockState({ lockLevel: 'system' })).toBe('protected')
    expect(resolveLayerLockState({ lockLevel: 'user' })).toBe('mine')
  })

  it('단순잠금(locked)은 mine, 아무것도 없으면 none', () => {
    expect(resolveLayerLockState({ locked: true })).toBe('mine')
    expect(resolveLayerLockState({})).toBe('none')
    expect(resolveLayerLockState({ movable: true, locked: false })).toBe('none')
  })

  it('보호가 단순잠금보다 우선 (locked + movable=false → protected)', () => {
    expect(resolveLayerLockState({ locked: true, movable: false })).toBe('protected')
  })
})

describe('layerDisplayName — 행 이름 규약 (L2 §5)', () => {
  it('사용자 지정 이름 우선', () => {
    expect(layerDisplayName({ name: '우리 아기 첫돌', type: SelectionType.text })).toBe('우리 아기 첫돌')
  })

  it('자동 이름(textbox3 등) + 텍스트면 내용 미리보기', () => {
    expect(
      layerDisplayName({ name: 'textbox3', type: SelectionType.text, textPreview: '안녕하세요 제목입니다' })
    ).toBe('안녕하세요 제목입니다')
  })

  it('미리보기 20자 초과는 말줄임', () => {
    const long = '가'.repeat(30)
    expect(layerDisplayName({ name: 'textbox1', type: SelectionType.text, textPreview: long })).toBe(
      `${'가'.repeat(20)}…`
    )
  })

  it('자동 이름 + 비텍스트는 타입 한국어명', () => {
    expect(layerDisplayName({ name: 'image0', type: SelectionType.image })).toBe('사진')
    expect(layerDisplayName({ name: 'rect12', type: SelectionType.shape })).toBe('도형')
    expect(layerDisplayName({ name: undefined, type: SelectionType.frame })).toBe('사진틀')
  })

  it('숫자 없는 소문자 사용자 이름(logo)은 그대로 표시', () => {
    expect(layerDisplayName({ name: 'logo', type: SelectionType.image })).toBe('logo')
  })

  it('isAutoGeneratedName 판정 — 한국어/공백 포함 이름은 사용자 지정으로 본다', () => {
    expect(isAutoGeneratedName('textbox3')).toBe(true)
    expect(isAutoGeneratedName('i-text2')).toBe(true)
    expect(isAutoGeneratedName('로고')).toBe(false)
    expect(isAutoGeneratedName('My Title')).toBe(false)
    // 적대 리뷰 major: 숫자 없는 소문자 영단어는 사용자 지정 이름 — 보존해야 한다
    expect(isAutoGeneratedName('logo')).toBe(false)
    expect(isAutoGeneratedName('cover')).toBe(false)
  })
})

describe('selectionTypeLabel — ControlBar/행 이름 단일 소스', () => {
  it('multiple 은 개수 표기', () => {
    expect(selectionTypeLabel(SelectionType.multiple, 3)).toBe('3개의 요소')
  })
  it('기본 폴백은 요소', () => {
    expect(selectionTypeLabel('unknown-type')).toBe('요소')
  })
})
