/**
 * L2 (2026-07-06): 레이어 행 표시 계층 — 잠금 2어휘 렌즈 + 행 이름 규약.
 * 설계 정본 LAYER_UX_REDESIGN_2026-07-06.md §2(재설계 원칙)·§3 A-2/A-3·§5(용어 통일).
 *
 * - 잠금 어휘 재편: 내부 3계층(단순잠금 / movable·deleteable·contentEditable·lockLayerOrder /
 *   lockInfo 레벨)을 사용자 개념 딱 둘로 통합 — "내 잠금"(본인이 걸고 즉시 푸는 것) vs
 *   "템플릿 보호"(디자이너가 걸고 고객은 못 푸는 것). 표시 계층 전용 — 저장/직렬화 무접촉.
 * - 행 이름: 사용자가 지정한 이름 우선. 자동 생성 이름(fabric type+index)은 텍스트면
 *   내용 미리보기, 나머지는 타입 한국어명으로 표시(display-only — fabric name 저장값 불변).
 */
import { SelectionType, type CanvasObject } from '@storige/canvas-core'

export type LayerLockState = 'none' | 'mine' | 'protected'

/**
 * 레이어 행의 잠금 상태 2어휘 판정 (표시 계층 공용 렌즈).
 * - protected: 디자이너 보호(위치고정/삭제잠금/내용잠금) 또는 designer+ 레벨 고급잠금
 * - mine: 그 외의 잠금(고객 단순잠금·user 레벨 고급잠금) — 본인이 항상 해제 가능
 */
export function resolveLayerLockState(o: {
  locked?: boolean
  movable?: boolean
  deleteable?: boolean
  contentEditable?: boolean
  lockLevel?: CanvasObject['lockLevel']
}): LayerLockState {
  const isProtected =
    o.movable === false ||
    o.deleteable === false ||
    o.contentEditable === false ||
    (o.lockLevel !== undefined && o.lockLevel !== 'user')
  if (isProtected) return 'protected'
  if (o.locked || o.lockLevel === 'user') return 'mine'
  return 'none'
}

/** SelectionType → 타입 한국어명. ControlBar getObjectName 과 단일 소스(§5 용어 동기화). */
export function selectionTypeLabel(type: SelectionType | string, count = 1): string {
  switch (type) {
    case SelectionType.text:
      return '텍스트'
    case SelectionType.image:
      return '사진'
    case SelectionType.shape:
      return '도형'
    case SelectionType.frame:
      return '사진틀'
    case SelectionType.background:
      return '배경'
    case SelectionType.smartCode:
      return 'QR/바코드'
    case SelectionType.group:
      return '그룹'
    case SelectionType.multiple:
      return `${count}개의 요소`
    case SelectionType.templateElement:
      return '템플릿 요소'
    default:
      return '요소'
  }
}

/**
 * fabric 자동 생성 이름 판정 — updateObjects 가 미명명 객체에 채우는 `obj.type + index`
 * (예: textbox3, image0, rect12, i-text2) 만 해당. 끝 숫자 필수(\d+) — 'logo'·'cover' 같은
 * 소문자 영단어 사용자 지정 이름을 오탐하지 않는다(적대 리뷰 major).
 */
const AUTO_NAME_RE = /^[a-z][a-z-]*\d+$/

export function isAutoGeneratedName(name: string | undefined): boolean {
  if (!name) return true
  return AUTO_NAME_RE.test(name.trim())
}

/**
 * 레이어 행 표시명 (display-only — 저장되는 fabric name 은 건드리지 않는다).
 * 우선순위: 사용자 지정 이름 > 텍스트 내용 미리보기 > 타입 한국어명.
 */
export function layerDisplayName(o: {
  name?: string
  type?: CanvasObject['type']
  textPreview?: string
}): string {
  if (o.name && !isAutoGeneratedName(o.name)) return o.name
  const preview = (o.textPreview || '').trim()
  if (preview) return preview.length > 20 ? `${preview.slice(0, 20)}…` : preview
  return selectionTypeLabel(o.type ?? '')
}
